global:
  # The Slack webhook URL.
  slack_api_url: '<slack_webhook_url>'

route:
  group_by: [alertname]
  receiver: slack-notifications

receivers:
- name: slack-notifications
  slack_configs:
    # The channel or user to send notifications to.
  - channel: #monitoring

    # API request data as defined by the Slack webhook API.
    icon_url: https://avatars3.githubusercontent.com/u/3380462

    # Whether or not to notify about resolved alerts.
    send_resolved: true

    # The text title of the slack notification.
    title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"

    # The text body of the slack notification.
    text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
