---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    storage: prometheus
  name: ocp-np-prometheus-volume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 150Gi
  nfs:
    path: /nfs/ocp-np-prometheus
    server: ctnfs01.bue299.comafi.com.ar
  persistentVolumeReclaimPolicy: Retain
status: {}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    storage: alertmanager
  name: ocp-np-alertmanager-volume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  nfs:
    path: /nfs/ocp-np-alertmanager
    server: ctnfs01.bue299.comafi.com.ar
  persistentVolumeReclaimPolicy: Retain
status: {}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    storage: alertbuffer
  name: ocp-np-alertbuffer-volume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  nfs:
    path: /nfs/ocp-np-alertbuffer
    server: ctnfs01.bue299.comafi.com.ar
  persistentVolumeReclaimPolicy: Retain
status: {}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    storage: grafana
  name: ocp-np-grafana-volume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  nfs:
    path: /nfs/ocp-np-grafana
    server: ctnfs01.bue299.comafi.com.ar
  persistentVolumeReclaimPolicy: Retain
status: {}
---
