---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-webhook-claim
spec:
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      storage: prometheus-logfiles
status: {}
