---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: kube-state-metrics
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kube-state-metrics
    spec:
      containers:
      - name: kube-state-metrics
        image: docker.io/redhatcsargentina/kube-state-metrics:v1.4.0
        imagePullPolicy: IfNotPresent
        Ports:
        - containerPort: 8080
      serviceAccount: kube-state-metrics
